#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -o output/

echo "Running job script"
module load python

python find_protoclusters.py 5p03 mstar
python find_protoclusters.py 3p95 mstar
python find_protoclusters.py 3p10 mstar
python find_protoclusters.py 2p07 mstar
# python find_protoclusters.py 6p42 sfr 
# python find_protoclusters.py 5p03 sfr
# python find_protoclusters.py 3p95 sfr
# python find_protoclusters.py 3p10 sfr
# python find_protoclusters.py 2p07 sfr 

echo "Finished job script"
